### ISSUE TITLE
getUserData does not return valid user

### ISSUE THREAD

**Issue by peeech** [HoloDen/mutual-rating#9]
After successful signup with help of enrollUser() calling to function getUserData() is returning {success: false}, while should return {success: true, user: userData}.

Obviously there's an inconsistency in the way anchor is created and then searched for.

**Comment by skjena** [comment]
Thanks for the notification!

New test file is under `backend/tests` as `users.json`, tests all enrollment functions. Also debug messages added as Status reports designated for each Zome for easier understanding.

I've attached a log output of running `hcdev test users` alongside this
[report.txt](https://github.com/HoloDen/mutual-rating/files/2513031/report.txt)
